//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockmanagerApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockManagerDBEntities : DbContext
    {
        public StockManagerDBEntities()
            : base("name=StockManagerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DISPATCH> DISPATCH { get; set; }
        public virtual DbSet<DISPATCH_STATE> DISPATCH_STATE { get; set; }
        public virtual DbSet<SALE> SALE { get; set; }
        public virtual DbSet<SALE_STATE> SALE_STATE { get; set; }
        public virtual DbSet<STOCK> STOCK { get; set; }
        public virtual DbSet<STOCK_STATE> STOCK_STATE { get; set; }
        public virtual DbSet<SUCURSAL> SUCURSAL { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<STOCK_SUCURSAL> STOCK_SUCURSAL { get; set; }
    }
}
