//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockmanagerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_SUCURSAL
    {
        public int IdSucursal { get; set; }
        public long IdStock { get; set; }
        public int Unity { get; set; }
    
        public virtual STOCK STOCK { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
