CREATE TABLE SUCURSAL(
 ID INT NOT NULL IDENTITY(1,1),
 Name NVARCHAR(200),
 Address NVARCHAR(500),
 PostalCode INT,
 CONSTRAINT P_SUCURSAL PRIMARY KEY(ID)
)
CREATE TABLE STOCK_STATE(
	ID INT NOT NULL IDENTITY(1,1),
	Description NVARCHAR(200),
	CONSTRAINT P_STOCK_STATE PRIMARY KEY(ID)
)

CREATE TABLE USUARIO(
	ID INT NOT NULL IDENTITY(1,1),
	UserName NVARCHAR(100) NOT NULL,
	Password NVARCHAR(10) NOT NULL,
	Name NVARCHAR(200) NOT NULL,
	LASTNAME NVARCHAR(200) NOT NULL,
	DateBorn DATETIME NOT NULL,
	DateAdmission DATETIME NOT NULL,
	Email NVARCHAR(500),
	Address NVARCHAR(500) NOT NULL,
	PostalCode INT NOT NULL,
	IdSucursal INT NOT NULL,
	CONSTRAINT P_USUARIO PRIMARY KEY(ID),
	 CONSTRAINT FK_USUARIO_SUCURSAL FOREIGN KEY (IdSucursal) REFERENCES SUCURSAL(ID)

)

CREATE TABLE SALE_STATE(
	ID INT NOT NULL IDENTITY(1,1),
	Description NVARCHAR(200),
	CONSTRAINT P_SALE_STATE PRIMARY KEY(ID),
)


CREATE TABLE SALE(
	ID INT NOT NULL IDENTITY(1,1),
	DateProces DATETIME NOT NULL,
	IdUser INT NOT NULL,
	Amount FLOAT NOT NULL,
	Refer NVARCHAR(MAX) NOT NULL,
	IdSUcursal INT NOT NULL,
	IdState INT NOT NULL,
	CONSTRAINT P_SALE PRIMARY KEY(ID),
	CONSTRAINT FK_SALE_SUCURSAL FOREIGN KEY (IdSucursal) REFERENCES SUCURSAL(ID),
	CONSTRAINT FK_SALE_USUARIO FOREIGN KEY (IdUser) REFERENCES USUARIO(ID),
	CONSTRAINT FK_SALE_SALESTATE FOREIGN KEY (IdState) REFERENCES SALE_STATE(ID)
)
CREATE TABLE SALE_STOCK(
	IdSale INT NOT NULL,
	IdStock INT NOT NULL,
	CONSTRAINT FK_SALE_STOCK_SALE FOREIGN KEY (IdSale) REFERENCES SALE(ID),
	CONSTRAINT FK_SALE_STOCK_SUCURSAL FOREIGN KEY (IdStock) REFERENCES SUCURSAL(ID)

)


CREATE TABLE DISPATCH_STATE(
	ID INT NOT NULL IDENTITY(1,1),
	Description NVARCHAR(200),
	CONSTRAINT P_DISPATCH_STATE PRIMARY KEY(ID)
)


CREATE TABLE STOCK(
 ID BIGINT NOT NULL IDENTITY(1,1),
 Code NVARCHAR(50) NOT NULL,
 QR NVARCHAR(100) NOT NULL,
 Name NVARCHAR(200) NOT NULL,
 Brand NVARCHAR(200) NOT NULL,
 Model NVARCHAR(100)NOT NULL,
 IdSucursal INT NOT NULL,
 IdState INT NOT NULL,
 Description NVARCHAR(MAX),
CONSTRAINT P_STOCK PRIMARY KEY(ID),
 CONSTRAINT FK_STOCK_SUCURSAL FOREIGN KEY (IdSucursal) REFERENCES SUCURSAL(ID),
 CONSTRAINT FK_STOCK_STOCK_STATE FOREIGN KEY (IdState) REFERENCES STOCK_STATE(ID)

)



CREATE TABLE STOCK_SUCURSAL(
	IdSucursal INT NOT NULL,
	IdStock BIGINT NOT NULL,
	Unity INT NOT NULL,
	 CONSTRAINT FK_STOCK_SUCURSAL_SUCURSAL FOREIGN KEY (IdSucursal) REFERENCES SUCURSAL(ID),
	 CONSTRAINT FK_STOCK_SUCURSAL_STOCK FOREIGN KEY (IdStock) REFERENCES STOCK(ID)
)





CREATE TABLE DISPATCH(
	ID INT NOT NULL IDENTITY(1,1),
	DateCreate DATETIME NOT NULL,
	IdUser INT NOT NULL,
	Origin INT NOT NULL,
	Destiny INT NOT NULL,
	IdState INT NOT NULL,
	DateDispatched INT NOT NULL,
	DateRecived INT NOT NULL,
	Unity INT NOT NULL,
	CONSTRAINT P_DISPATCH PRIMARY KEY(ID),
	CONSTRAINT FK_DISPATCH_DISPATCH_STATE FOREIGN KEY (IdState) REFERENCES DISPATCH_STATE(ID),
	CONSTRAINT FK_DISPATCH_USUARIO FOREIGN KEY (IdUser) REFERENCES DISPATCH_STATE(ID)


)
