CREATE TABLE [STOCK_SUCURSAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IdSucursal] [int] NOT NULL,
	[IdStock] [bigint] NOT NULL,
	[Unity] [int] NOT NULL,
	 CONSTRAINT PK_STOCK_SUCURSAL PRIMARY KEY (ID),
	 CONSTRAINT FK_STOCK_SUCURSAL_SUCURSAL FOREIGN KEY (IdSucursal) REFERENCES SUCURSAL(ID),
	 CONSTRAINT FK_STOCK_SUCURSAL_STOCK FOREIGN KEY (IdStock) REFERENCES STOCK(ID)
)