CREATE TABLE [DISPATCH](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DateCreate] [datetime] NOT NULL,
	[IdUser] [int] NOT NULL,
	[IdOrigin] [int] NOT NULL,
	[IdDestiny] [int] NOT NULL,
	[IdState] [int] NOT NULL,
	[DateDispatched] [datetime]  NULL,
	[DateReceived] [datetime]  NULL,
	[Unity] [int] NOT NULL,
	 CONSTRAINT PK_DISPATCH PRIMARY KEY (ID),
	 CONSTRAINT FK_DISPATCH_USERSORIGIN FOREIGN KEY (IdUser) REFERENCES USERS(ID),
	 CONSTRAINT FK_DISPATCH_DISPATCH_STATE FOREIGN KEY (IdState) REFERENCES DISPATCH_STATE(ID),
	 CONSTRAINT FK_DISPATCH_OFFICE_ORIGIN FOREIGN KEY (IdOrigin) REFERENCES OFFICE(ID),
	 CONSTRAINT FK_DISPATCH_OFFICE_DESTINY FOREIGN KEY (IdDestiny) REFERENCES OFFICE(ID)
	
)
