CREATE TABLE [dbo].[ROLES_PERMISSION](
	[IdRole] [int] NOT NULL,
	[IdPermission] [int] NOT NULL,
	[Read] [int] NOT NULL,
	[Write] [int] NOT NULL,
	 CONSTRAINT FK_ROLES_PERMISSION_ROLES FOREIGN KEY (IdRole) REFERENCES ROLES(ID),
	 CONSTRAINT FK_ROLES_PERMISSION_PERMISSION FOREIGN KEY (IdPermission) REFERENCES PERMISSION(ID)
)
