CREATE TABLE [HISTORY](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[DateProces] [datetime] NOT NULL,
	[IdUser] [int] NOT NULL,
	[IdOffice] [int] NOT NULL,
	[IdAction] [int] NOT NULL,
	[SubAction] [nvarchar](300) NOT NULL,
	[ActionDetail] [nvarchar](max) NOT NULL,
	 CONSTRAINT PK_HISTORY PRIMARY KEY (ID),
	  CONSTRAINT FK_HISTORY_OFFICE FOREIGN KEY (IdOffice) REFERENCES OFFICE(ID),
	 CONSTRAINT FK_HISTORY_USERS FOREIGN KEY (IdUser) REFERENCES USERS(ID),
	 CONSTRAINT FK_HISTORY_ACTIONS FOREIGN KEY (IdAction) REFERENCES ACTIONS(ID)
	
 
 )

