CREATE TABLE DISCOUNT_PAYMENTTYPE(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IdPayMentType] [int] NOT NULL,	
	[IdDiscount] [BigInt] NOT NULL

	 CONSTRAINT PK_DISCOUNT_PAYMENTTYPE PRIMARY KEY (ID),
	 CONSTRAINT FK_DISCOUNT_PAYMENTTYPE_PAYTMENTTYPE FOREIGN KEY (IdPayMentType) REFERENCES PAYMENTTYPE(ID),
	 CONSTRAINT FK_DISCOUNT_PAYMENTTYPE_DISCOUNT FOREIGN KEY (IdDiscount) REFERENCES DISCOUNT(ID)
	 
)